### PR TITLE
Check for virtual keyboard support on switch

### LINKED ISSUE #4: Switch version keyboard does not work on Applet mode
The virtual keyboard does not show up if you start the game from an "Applet mode" hbmenu.

I think this is an intended limitation, but it does make it impossible to create a new player, maybe it should fall back to an auto-generated name?

### PR DESCRIPTION
**Pull request by rjimenezda**
Fix #4 

Originally I planned to check the return value of the `inputVirtualKeyboardText` function, and fall back to the auto generated one if it failed. Unfortunately, SwKbd fails the same way whether it's an error when creating it or when the user cancels the interaction.

In order to support the cancelation flow, we would have to use InlineKbd, but that's an entirely different flow I'm afraid.

In any case, the check on the conditional should fix the problem I encountered and auto generate a player name for you if you run it on Applet mode :smile:

### CODE REVIEW

File: src/conditionals.c [hunk 1]
```diff
@@ -28,8 +32,12 @@ uint8_t supportsRealKeyboard(void)
 
 uint8_t supportsVirtualKeyboard(void)
 {
-#if defined(__vita__) || defined(__SWITCH__) || defined(_3DS) || defined(__PSL1GHT__)
+#if defined(__vita__) || defined(_3DS) || defined(__PSL1GHT__)
     return 1;
+#elif defined(__SWITCH__)
+    // If app is ran in applet mode, SwKbd will not work
+    AppletType at = appletGetAppletType();
+    return at == AppletType_Application || at == AppletType_SystemApplication ? 1 : 0;
```
Comment (sergiou87) [inline src/conditionals.c:40]: I think you can just do this?
```suggestion
    return at == AppletType_Application || at == AppletType_SystemApplication;
```

File: src/nx/nxVirtualKeyboard.c [hunk 2]
```diff
@@ -89,8 +89,12 @@ uint8_t inputVirtualKeyboardText(const char *title, uint16_t maxLength, char *ou
             strncpy(outText, tmpoutstr, maxLength);
 
             success = 1;
+        } else {
+            spLogInfo("Failed to show software keyboard"); 
         }
         swkbdClose(&kbd);
+    } else {
+        spLogInfo("Failed to create software keyboard");
```
Comment (sergiou87) [inline src/nx/nxVirtualKeyboard.c:97]: Sorry about this nit 😂 but I'm loyal to the K&R style for curly braces 😅 
```suggestion
        }
        else
        {
            spLogInfo("Failed to show software keyboard"); 
        }
        swkbdClose(&kbd);
    }
    else
    {
        spLogInfo("Failed to create software keyboard"); 
```

**Comment by sergiou87** [comment]
BTW I can take care of those small fixes if you don't have time or whatever, if so just let me know and I'll gladly make those changes and merge it 😄

File: src/conditionals.c (hunk 1 above)
Comment (rjimenezda) [reply src/conditionals.c:40]: My C is kind of rusty, and was being paranoid, you are totally right 👍

File: src/nx/nxVirtualKeyboard.c (hunk 2 above)
Comment (rjimenezda) [reply src/nx/nxVirtualKeyboard.c:97]: Oh no, my bad, I didn't pay too much attention to the code style 😓

**Comment by rjimenezda** [comment]
> Thank you for this!! I didn't even know there were differences between regular apps and applets (other than the amount of memory available).
> 
> I just made a couple of small suggestions, other than that LGTM!

I didn't either, to be honest, I had to dig through nx-hbmenu and retroarch to be sure the check was the right one 😄 

I'm just happy I can play supaplex on my Switch 🎉 🎉

**Comment by sergiou87** [comment]
🎉 I just kicked a nightly build with your fix, should be available in https://github.com/sergiou87/open-supaplex/releases/tag/nightly in a few minutes 😄 

I might have other things to fix in other (or all) platforms, so I'll wait a bit before releasing a 7.1.2 or 7.2 version.

Thanks again for your contribution 🙇‍♂️
