### PR TITLE
Linux: Fix Wayland crash on events before setup done

### LINKED ISSUE #66: Linux (wayland?) crash
I get a crash on linux because `gTexture` in call to `SDL_UpdateTexture` is `NULL`. `gTextureSurface` is `NULL` as well. The program didn't exit at `initializeVideo` even though these seem to be checked later on.

The issue is that on wayland, SDL registers event listeners with `SDL_CreateRenderer`, resize event is dispatched right then, which calls `render` before these globals are set.

<details>
<summary>Stack Trace</summary>
```c++
../src/sdl2/video.c:148: SDL_UpdateTexture(gTexture, NULL, gTextureSurface->pixels, gTextureSurface->pitch);

#0  render () at ../src/sdl2/video.c:148
#1  0x000055555557c4b7 in windowResizingEventWatcher (data=0x555555670650, event=0x7fffffffbaa0) at ../src/sdl2/video.c:260
#2  0x00007ffff7eebc3e in EventFilter3to2 (userdata=<optimized out>, event3=0x7fffffffbe10) at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.56/src/sdl2_compat.c:2774
#3  EventFilter3to2 (userdata=<optimized out>, event3=0x7fffffffbe10) at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.56/src/sdl2_compat.c:2720
#4  0x00007ffff784e6cd in SDL_DispatchEventWatchList (list=0x7ffff7a9ed80 <SDL_event_watchers.lto_priv.0>, event=event@entry=0x7fffffffbe10)
    at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_eventwatch.c:64
#5  0x00007ffff784e83e in SDL_CallEventWatchers (event=0x7fffffffbe10) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_events.c:1710
#6  SDL_CallEventWatchers (event=0x7fffffffbe10) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_events.c:1704
#7  SDL_PushEvent_REAL (event=0x7fffffffbe10) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_events.c:1719
#8  0x00007ffff7ee3d65 in SDL_PushEvent_REAL (event2=event2@entry=0x7fffffffbf40) at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.56/src/sdl2_compat.c:2591
#9  0x00007ffff7eec4d4 in EventFilter3to2 (userdata=<optimized out>, event3=<optimized out>) at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.56/src/sdl2_compat.c:2851
#10 EventFilter3to2 (userdata=<optimized out>, event3=<optimized out>) at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.56/src/sdl2_compat.c:2720
#11 0x00007ffff784e6cd in SDL_DispatchEventWatchList (list=0x7ffff7a9ed80 <SDL_event_watchers.lto_priv.0>, event=event@entry=0x7fffffffc2d0)
    at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_eventwatch.c:64
#12 0x00007ffff784e83e in SDL_CallEventWatchers (event=0x7fffffffc2d0) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_events.c:1710
#13 SDL_CallEventWatchers (event=0x7fffffffc2d0) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_events.c:1704
#14 SDL_PushEvent_REAL (event=0x7fffffffc2d0) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_events.c:1719
#15 0x00007ffff78585ba in SDL_SendWindowEvent.isra.0 (window=window@entry=0x555555670650, windowevent=windowevent@entry=SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, 
    data1=<optimized out>, data2=<optimized out>) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_windowevents.c:236
#16 0x00007ffff793a7f6 in SDL_CheckWindowPixelSizeChanged (window=0x555555670650) at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/SDL_video.c:4005
#17 SDL_OnWindowResized (window=0x555555670650) at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/SDL_video.c:3989
#18 0x00007ffff78587c8 in SDL_SendWindowEvent.isra.0 (window=window@entry=0x555555670650, windowevent=windowevent@entry=SDL_EVENT_WINDOW_RESIZED, 
    data1=<optimized out>, data2=<optimized out>) at /usr/src/debug/sdl3/SDL3-3.2.16/src/events/SDL_windowevents.c:250
#19 0x00007ffff7998251 in ConfigureWindowGeometry (window=0x555555670650) at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/wayland/SDL_waylandwindow.c:452
#20 0x00007ffff7998742 in handle_configure_xdg_shell_surface (data=0x55555583edd0, xdg=0x55555583fcd0, serial=100516)
    at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/wayland/SDL_waylandwindow.c:752
#21 0x00007ffff7b42ac6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#22 0x00007ffff7b3f76b in ffi_call_int (cif=cif@entry=0x7fffffffc820, fn=fn@entry=0x7ffff7998720 <handle_configure_xdg_shell_surface>, rvalue=<optimized out>, 
    rvalue@entry=0x0, avalue=avalue@entry=0x7fffffffc8f0, closure=closure@entry=0x0) at ../src/x86/ffi64.c:676
#23 0x00007ffff7b4206e in ffi_call (cif=cif@entry=0x7fffffffc820, fn=0x7ffff7998720 <handle_configure_xdg_shell_surface>, rvalue=rvalue@entry=0x0, 
    avalue=avalue@entry=0x7fffffffc8f0) at ../src/x86/ffi64.c:713
#24 0x00007ffff7b4b910 in wl_closure_invoke (closure=closure@entry=0x555555840010, target=<optimized out>, target@entry=0x55555583fcd0, opcode=opcode@entry=0, 
    data=<optimized out>, flags=1) at ../wayland-1.23.1/src/connection.c:1228
#25 0x00007ffff7b4c199 in dispatch_event (display=display@entry=0x55555566fdf0, queue=queue@entry=0x55555566fee8) at ../wayland-1.23.1/src/wayland-client.c:1674
#26 0x00007ffff7b4c573 in dispatch_queue (display=0x55555566fdf0, queue=0x55555566fee8) at ../wayland-1.23.1/src/wayland-client.c:1820
--Type <RET> for more, q to quit, c to continue without paging--
#27 wl_display_dispatch_queue_pending (display=0x55555566fdf0, queue=0x55555566fee8) at ../wayland-1.23.1/src/wayland-client.c:2062
#28 0x00007ffff79a0fe4 in Wayland_ShowWindow (_this=0x555555683820, window=0x555555670650)
    at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/wayland/SDL_waylandwindow.c:2003
#29 0x00007ffff79360cc in SDL_ShowWindow_REAL (window=0x555555670650) at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/SDL_video.c:3260
#30 SDL_ShowWindow_REAL (window=0x555555670650) at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/SDL_video.c:3244
#31 0x00007ffff7939791 in SDL_RecreateWindow (window=0x555555670650, flags=34) at /usr/src/debug/sdl3/SDL3-3.2.16/src/video/SDL_video.c:2734
#32 0x00007ffff789bba0 in GL_CreateRenderer (renderer=0x55555568a680, window=0x555555670650, create_props=8)
    at /usr/src/debug/sdl3/SDL3-3.2.16/src/render/opengl/SDL_render_gl.c:1645
#33 0x00007ffff788476e in SDL_CreateRendererWithProperties_REAL (props=props@entry=8) at /usr/src/debug/sdl3/SDL3-3.2.16/src/render/SDL_render.c:1037
#34 0x00007ffff7884957 in SDL_CreateRenderer_REAL (window=0x555555670650, name=0x0) at /usr/src/debug/sdl3/SDL3-3.2.16/src/render/SDL_render.c:1166
#35 0x00007ffff7ee76d9 in SDL_CreateRenderer_REAL (window=0x555555670650, idx=<optimized out>, flags=6)
    at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.56/src/sdl2_compat.c:5814
#36 0x000055555557bf7f in initializeVideo (fastMode=0 '\000') at ../src/sdl2/video.c:91
#37 0x0000555555563370 in main (argc=1, argv=0x7fffffffcf18) at ../src/supaplex.c:1525
```
</details>

Adding a guard bool which early returns from the `render()` function unless `initializeVideo()` function is done seems to fix this issue.

### PR DESCRIPTION
**Pull request by Caellian**
Game crashed because SDL_CreateRenderer would setup Wayland event listeners which could get called before initializeVideo finishes. Resize event on tiling WMs presumably always crashes the game because it calls render before gTexture and other variables are initialized.

Fixes #66.

### CODE REVIEW

File: src/sdl2/video.c [hunk 1]
```diff
@@ -143,6 +143,8 @@ void initializeVideo(uint8_t fastMode)
 
 void render()
 {
+    if (!gScreenSurface) return;
```
Comment (sergiou87) [inline src/sdl2/video.c:146]:
```suggestion
    // In some cases (like using Wayland on Linux) some SDL events could be triggered
    // and end up triggering a render before initializeVideo is done.
    if (gScreenSurface == NULL)
    {
        return;
    }
```
